name: Rancher Layer-2 Flat
version: v0.1.4
description: |
  Rancher Networking plugin using Layer-2 Flat.
category: Networking
labels:
  io.rancher.certified: Experimental
  io.rancher.orchestration.supported: 'cattle'
